apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: edu-roman-kolyada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: romigo24/django-site:e28d3c0
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres
              key: dsn
        - name: DJANGO_SETTINGS_MODULE
          value: "webapp.settings"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
        volumeMounts:
        - name: ssl-cert-volume
          mountPath: /root/.postgresql
          readOnly: true
      volumes:
      - name: ssl-cert-volume
        secret:
          secretName: postgres-ssl-cert
          defaultMode: 0600