apiVersion: v1
kind: ConfigMap
metadata:
  name: main-nginx-config
  namespace: edu-roman-kolyada
data:
  nginx.conf: |
    user nginx;
    worker_processes  2;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen       80;
        server_name  localhost;
        location / {
            return 200 'OK! It`s nginx in edu-roman-kolyada namespace'; 
        }
      }
    }