apiVersion: v1
kind: ConfigMap
metadata:
  name: main-nginx-config
  namespace: edu-roman-kolyada
data:
  nginx.conf: |
    user nginx;
    worker_processes  2;
    events {
      worker_connections  10240;
    }
    http {
      upstream django_backend {
        server django-service:8000;
      }

      server {
        listen 80;
        server_name edu-roman-kolyada.yc-sirius-dev.pelid.team;

        location / {
          proxy_pass http://django_backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

          proxy_connect_timeout 30s;
          proxy_send_timeout 30s;
          proxy_read_timeout 30s;
        }
      }
    }