apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  labels:
    app: django-app
    app.kubernetes.io/name: django-clearsessions
    app.kubernetes.io/component: maintenance
spec:
  schedule: "0 5 * * 1"
  startingDeadlineSeconds: 300
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: clearsessions
            image: django_app:latest
            imagePullPolicy: IfNotPresent
            command: ["python", "manage.py", "clearsessions"]
            env:
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "*"
            envFrom:
            - secretRef:
                name: django-secrets