apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    app: django-app
    app.kubernetes.io/name: django-migrate
    app.kubernetes.io/component: database
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: django_app:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py", "migrate", "--no-input"]
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
        - name: DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: database-url
      restartPolicy: Never